### ISSUE TITLE
请问下 flask启动的那几个服务是做什么的？

### ISSUE THREAD

**Issue by vTNT** [pengzihe/cmdb#21]
端口5000， 5001这些干嘛的 还有consul 作用是？

**Comment by vTNT** [comment]
另外可以考虑支持下git

**Comment by pengzihe** [comment]
@vTNT 5001端口是自己手动指定端口号，默认是5000，consul这里只做查询借口，和cmdb项目没什么关系，代码本身就是支持git。

**Comment by vTNT** [comment]
你好， 麻烦请教个问题， 比如我现在发布个django项目，django底下需要配置setting.py， 那么如果需要发布到开发，测试，预发布，生产环境，则setting.py对应的配置就不一样， 请问这块怎么管理比较方便？

**Comment by pengzihe** [comment]
多配置文件可以用服务配置，key,value形式，比如etcd,consul都可以，可以保证配置文件在什么环境都一致，但是需要额外维护一套配置环境，比如consul,etcd服务

**Comment by vTNT** [comment]
好的 谢谢
